services:
    atcoder:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: atcoder
        stdin_open: true
        tty: true
        volumes:
            - ..:/workspace:cached
            - acc-config:/root/.config/atcoder-cli-nodejs
            - oj-config:/root/.local/share/online-judge-tools

volumes:
  acc-config:
  oj-config: